baseURL = "https://whatstack.tech/"
enableRobotsTXT = true
title = "Whatstack"

# Will give values to .Lastmod etc.
# enableGitInfo = true

# Language settings
contentDir = "content/cn"
defaultContentLanguage = "cn"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
author = "author"
category = "categories"
tag = "tags"

# First one is picked as the Twitter card image if not set on page.
#images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/blog/:slug/"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "tango"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true

# Image processing configuration.
[imaging]
anchor = "smart"
quality = 75
resampleFilter = "CatmullRom"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "G-JBYJP9EYZC"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"