
baseURL = "https://whatstack.tech/"
enableRobotsTXT = true
title = "Whatstack"

# Will give values to .Lastmod etc.
# enableGitInfo = true

# Language settings
contentDir = "content/cn"
defaultContentLanguage = "cn"
defaultContentLanguageInSubdir = false
# Useful when translating.
enableMissingTranslationPlaceholders = true

# Comment out to disable taxonomies in Docsy
# disableKinds = ["taxonomy", "taxonomyTerm"]

# You can add your own taxonomies
[taxonomies]
author = "author"
category = "categories"
tag = "tags"

[params.taxonomy]
# set taxonomyCloud = [] to hide taxonomy clouds
taxonomyCloud = []

# If used, must have same lang as taxonomyCloud
taxonomyCloudTitle = ["Tag Cloud", "Categories", "Authors"]

# set taxonomyPageHeader = [] to hide taxonomies on the page headers
taxonomyPageHeader = ["tags", "categories", "authors"]

# Highlighting config
pygmentsCodeFences = true
pygmentsUseClasses = false
# Use the new Chroma Go highlighter in Hugo.
pygmentsUseClassic = false
#pygmentsOptions = "linenos=table"
# See https://help.farbox.com/pygments.html
pygmentsStyle = "tango"

# First one is picked as the Twitter card image if not set on page.
#images = ["images/project-illustration.png"]

# Configure how URLs look like per section.
[permalinks]
blog = "/blog/:slug/"

[markup.goldmark.renderer]
unsafe = true

[markup.highlight]
style = "tango"

## Configuration for BlackFriday markdown parser: https://github.com/russross/blackfriday
[blackfriday]
angledQuotes = false
hrefTargetBlank = false
latexDashes = true
plainIDAnchors = true

# Image processing configuration.
[imaging]
anchor = "smart"
quality = 75
resampleFilter = "CatmullRom"

[services]
[services.googleAnalytics]
# Comment out the next line to disable GA tracking. Also disables the feature described in [params.ui.feedback].
id = "G-JBYJP9EYZC"

# Language configuration

[languages]
[languages.cn]
description = "Fast Serverless Functions for Kubernetes"
languageName = "中文"
title = "Whatstack"
# Weight used for sorting.
weight = 1

# Everything below this are Site Params

[params]
books_directory = "content/cn/docs"
copyright = "Copyright © 2023 Whatstack"
privacy_policy = ""

# Google Custom Search Engine ID. Remove or comment out to disable search.
# gcs_engine_id = "c632b781ffe71b197"
algolia_docsearch = true

# current release branch - could be rc
release_branch = "main"
# the main version. Never is rc.
release_version = "v1.19.0"

slackurl = "/slack"

installurl = '/docs/installation/'
learnmoreurl = '/docs/installation/'
twitterurl = 'https://twitter.com/fissionio'

notoc = true

# First one is picked as the Twitter card image if not set on page.
images = ["images/og-image-fission.png"]

disqusShortname = 'whatstack'
hide_feedback= false

[params.gitment]
owner="lanceMe"
repo="Whatstack"
client_id='6643231c7e90fc76b8af'
client_secret='803db82b34bea53a83092930edd6c69aee532d9d'


[params.social]
github = 'fission'
slackurl = "/slack"
twitter = 'fissionio'


# User interface configuration
[params.ui]
#  Set to true to disable breadcrumb navigation.
breadcrumb_disable = false
# Set to true to disable the About link in the site footer
footer_about_disable = false
# Set to false if you don't want to display a logo (/assets/icons/logo.svg) in the top navbar
navbar_logo = true
# Set to true if you don't want the top navbar to be translucent when over a `block/cover`, like on the homepage.
navbar_translucent_over_cover_disable = false
# Enable to show the side bar menu in its compact state.
sidebar_menu_compact = true
# Set to true to hide the sidebar search box (the top nav search box will still be displayed if search is enabled)
sidebar_search_disable = false

# Adds a H2 section titled "Feedback" to the bottom of each doc. The responses are sent to Google Analytics as events.
# This feature depends on [services.googleAnalytics] and will be disabled if "services.googleAnalytics.id" is not set.
# If you want this feature, but occasionally need to remove the "Feedback" section from a single page,
# add "hide_feedback: true" to the page's front matter.
[params.ui.feedback]
enable = true
# The responses that the user sees after clicking "yes" (the page was helpful) or "no" (the page was not helpful).
no = 'Sorry to hear that. Please <a href="https://github.com/whatstack-tech/whatstack.tech/issues/new">tell us how we can improve</a>.'
yes = 'Glad to hear it! Please <a href="https://github.com/whatstack-tech/whatstack.tech/issues/new">tell us how we can improve</a>.'

# Adds a reading time to the top of each doc.
# If you want this feature, but occasionally need to remove the Reading time from a single page, 
# add "hide_readingtime: true" to the page's front matter
[params.ui.readingtime]
enable = false

[params.links]
# End user relevant links. These will show up on left side of footer and in the community page if you have one.
[[params.links.user]]
desc = "Development takes place here!"
icon = "fab fa-github"
name = "GitHub"
url = "https://github.com/whatstack-tech/whatstack.tech"

[sitemap]
changefreq = "monthly"
filename = "sitemap.xml"
priority = 0.5

# 菜单
[menu]
[[menu.main]]
name = "主页"
url = "/"
pre = "<i class='fas fa-book'></i>"
weight = 10
[[menu.main]]
name = "文章"
url = "/blog/"
pre = "<i class='fas fa-blog'></i>"
weight = 20
[[menu.main]]
name = "Examples"
url = "/examples/"
pre = "<i class='fas fa-certificate'></i>"
weight = 30
[[menu.main]]
name = "GitHub"
url = "https://github.com/whatstack-tech/whatstack.tech"
pre = "<i class='fab fa-github'></i>"
weight = 40
[[menu.main]]
name = "支持"
url = "/support/"
pre = "<i class='fas fa-briefcase'></i>"
weight = 50

[module]
proxy = "direct"
[[module.imports]]
path = "github.com/google/docsy"
[[module.imports]]
path = "github.com/google/docsy/dependencies"
