[build]
command = "./build.sh"
publish = "public"

[context.production.environment]
HUGO_ENABLEGITINFO = "true"
HUGO_ENV = "production"
HUGO_VERSION = "0.108.0"
GO_VERSION = "1.19.3"

[context.split1.environment]
HUGO_ENV = "production"
HUGO_VERSION = "0.108.0"
GO_VERSION = "1.19.3"

[context.deploy-preview.environment]
HUGO_VERSION = "0.108.0"
GO_VERSION = "1.19.3"

[context.branch-deploy.environment]
HUGO_VERSION = "0.108.0"
GO_VERSION = "1.19.3"

[context.next.environment]
HUGO_ENABLEGITINFO = "true"

